# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4702236f5a06fcc6399dc7848ce32720f4f5c846054a125da21766eee6dd116d175becfa2f93c1079b45a5b4334f0493132a9e6ffa1f51963c4b1c5990c0d04

test:
  secret_key_base: 338befcac12dfada375608353ee430899858d368bfd9af92cd23997eb4cbb84619ff90195af72a15a12794d6f14a28b343bc4e95af52233ba430af2af37c7577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
